server:
  port: 8083

eureka:
  client:
    enabled: false

spring:
  application:
    name: Kafka Producer Service App

  cloud:
    discovery:
      enabled: false
      
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ItemCreatedEvent:org.example.items_api_service.ItemCreatedEvent
    consumer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      group-id: item-created
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: org.example.items_api_service
        spring.json.type.mapping: ItemCreatedEvent:org.example.items_api_service.ItemCreatedEvent
      
application:
  kafka:
    topics:
      item-created:
        name: 'ItemCreated'
        partition-count: 1
        replication-factor: 1