server:
  port: 8081

spring:
  application:
    name: producer-service-app
  
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    prefer-ip-address: true